/*
 * Copyright 2014 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.07 at 04:43:56 PM EDT 
//


package org.oasis_open.docs.s_ramp.ns.s_ramp_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for BaseArtifactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseArtifactType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}BaseArtifactType">
 *       &lt;redefine>
 *         &lt;complexType name="BaseArtifactType">
 *           &lt;complexContent>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;sequence>
 *                 &lt;element ref="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}classifiedBy" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;element ref="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}relationship" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;element ref="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}property" maxOccurs="unbounded" minOccurs="0"/>
 *               &lt;/sequence>
 *               &lt;attribute name="artifactType" use="required" type="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}baseArtifactEnum" />
 *               &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;attribute name="createdBy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;attribute name="uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;attribute name="createdTimestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;attribute name="lastModifiedTimestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;attribute name="lastModifiedBy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;anyAttribute/>
 *             &lt;/restriction>
 *           &lt;/complexContent>
 *         &lt;/complexType>
 *       &lt;/redefine>
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}comment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseArtifactType", propOrder = {
    "comment"
})
@XmlSeeAlso({
    DerivedArtifactType.class,
    ExtendedArtifactType.class,
    DocumentArtifactType.class
})
public abstract class BaseArtifactType
    extends OriginalBaseArtifactType
    implements Serializable
{

    private static final long serialVersionUID = 8039052591234659752L;
    protected List<Comment> comment;

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Comment }
     * 
     * 
     */
    public List<Comment> getComment() {
        if (comment == null) {
            comment = new ArrayList<Comment>();
        }
        return this.comment;
    }

}
