/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 02:36:46 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://s-ramp.org/xmlns/2010/s-ramp", 
    xmlns = {   
        @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://s-ramp.org/xmlns/2010/s-ramp", prefix = "s-ramp"),
        @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.w3.org/1999/xlink", prefix="xlink")
    },
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.s_ramp.xmlns._2010.s_ramp;
