//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 10:13:15 PM EDT 
//


package org.s_ramp.xmlns._2010.s_ramp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for baseArtifactEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="baseArtifactEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BaseArtifactType"/>
 *     &lt;enumeration value="DocumentArtifactType"/>
 *     &lt;enumeration value="DerivedArtifactType"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "baseArtifactEnum")
@XmlEnum
public enum BaseArtifactEnum {

    @XmlEnumValue("BaseArtifactType")
    BASE_ARTIFACT_TYPE("BaseArtifactType"),
    @XmlEnumValue("DocumentArtifactType")
    DOCUMENT_ARTIFACT_TYPE("DocumentArtifactType"),
    @XmlEnumValue("DerivedArtifactType")
    DERIVED_ARTIFACT_TYPE("DerivedArtifactType");
    private final String value;

    BaseArtifactEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BaseArtifactEnum fromValue(String v) {
        for (BaseArtifactEnum c: BaseArtifactEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
