//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.19 at 10:13:15 PM EDT 
//


package org.s_ramp.xmlns._2010.s_ramp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DerivedArtifactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DerivedArtifactType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://s-ramp.org/xmlns/2010/s-ramp}BaseArtifactType">
 *       &lt;sequence>
 *         &lt;element name="relatedDocument" type="{http://s-ramp.org/xmlns/2010/s-ramp}documentArtifactTarget"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DerivedArtifactType", propOrder = {
    "relatedDocument"
})
public abstract class DerivedArtifactType
    extends BaseArtifactType
{

    @XmlElement(required = true)
    protected DocumentArtifactTarget relatedDocument;

    /**
     * Gets the value of the relatedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentArtifactTarget }
     *     
     */
    public DocumentArtifactTarget getRelatedDocument() {
        return relatedDocument;
    }

    /**
     * Sets the value of the relatedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentArtifactTarget }
     *     
     */
    public void setRelatedDocument(DocumentArtifactTarget value) {
        this.relatedDocument = value;
    }

}
