/*
 * Copyright 2014 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.18 at 03:02:22 PM EST 
//


package org.oasis_open.docs.s_ramp.ns.s_ramp_v1;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for NamedWsdlDerivedArtifactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NamedWsdlDerivedArtifactType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}WsdlDerivedArtifactType">
 *       &lt;attribute name="NCName" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NamedWsdlDerivedArtifactType")
@XmlSeeAlso({
    WsdlService.class,
    Port.class,
    Part.class,
    Message.class,
    Fault.class,
    PortType.class,
    Operation.class,
    OperationInput.class,
    OperationOutput.class,
    Binding.class,
    BindingOperation.class,
    BindingOperationInput.class,
    BindingOperationOutput.class,
    BindingOperationFault.class
})
public abstract class NamedWsdlDerivedArtifactType
    extends WsdlDerivedArtifactType
    implements Serializable
{

    private static final long serialVersionUID = 4047408978475361449L;
    @XmlAttribute(name = "NCName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ncName;

    /**
     * Gets the value of the ncName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCName() {
        return ncName;
    }

    /**
     * Sets the value of the ncName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCName(String value) {
        this.ncName = value;
    }

}
